//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration_clients
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_training
    {
        public int IDShedule { get; set; }
        public string section { get; set; }
        public System.DateTime schedule { get; set; }
        public string trainer { get; set; }
    }
}
