//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration_clients
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int userID { get; set; }
        public string passwrd { get; set; }
        public int IDRole { get; set; }
        public int IDPerson { get; set; }
        public string phoneNumber { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Role Role { get; set; }
    }
}
